# This is a basic workflow to help you get started with Actions

name: CI - PDFLatex build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: LaTeX compilation
      uses: dante-ev/latex-action@master
      with:
        # The root LaTeX file to be compiled
        root_file: main.tex
        # LaTeX engine to be used
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the latex compiler
#         args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
        # Install extra packages by apt-get
#         extra_system_packages: # optional

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: pdf
        path: main.pdf
        retention-days: 30
        if-no-files-found: error

    - name: Move file to a branch
      if: success() && github.ref == 'refs/heads/master'
      run: |
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git fetch --all
        git checkout pdf
        mv main.pdf quasar.pdf
        git add quasar.pdf
        git commit -m "pdf compile"
        git push origin pdf
